def outside1():
    print("succesfully called outside function 1")

def outside2():
    print("succesfully called outside function 2")
